[package]
name = "testcat"
version = "0.1.0"
edition = "2021"
authors = ["josephlenton@gmail.com <josephlenton@gmail.com>"]
license = "MIT"
description = "Macros for writing more readable tests"
repository = "https://github.com/JosephLenton/testcat"


[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.9"
syn = { version = "1.0.63", features = ["derive", "printing", "parsing", "full", "extra-traits"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
