[package]
name = "testcat"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.9"
syn = { version = "1.0.63", features = ["derive", "printing", "parsing", "full", "extra-traits"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
